
Test 1 - SELinux local - OK --------------------------------------------------
                     selinux_plugin.setup                -    DEBUG:  SELinux_local - lanmonitor.selinux_plugin.setup() called:
  {'key': 'SELinux_local', 'tag': 'local', 'host': 'local', 'user_host_port': 'local', 'critical': True, 'cmd_timeout': 2, 'check_interval': 1, 'rest_of_line': '  enforcing  '}
                selinux_plugin_test.dotest               -    DEBUG:  SELinux_local - setup() returned:  0
                     selinux_plugin.eval_status          -    DEBUG:  SELinux_local - lanmonitor.selinux_plugin.eval_status() called
                        lanmonfuncs.cmd_check            -    DEBUG:  cmd try 1 <['sestatus']>
                selinux_plugin_test.dotest               -    DEBUG:  SELinux_local - eval_status() returned:  {'rslt': 0, 'notif_key': 'SELinux_local', 'message': 'SELinux_local  OK - local - enforcing'}

Test 2 - SELinux remote not running - ERROR --------------------------------------------------
                     selinux_plugin.setup                -    DEBUG:  SELinux_remote - lanmonitor.selinux_plugin.setup() called:
  {'key': 'SELinux_remote', 'tag': 'remote', 'host': 'testhost', 'user_host_port': 'me@testhost', 'critical': False, 'cmd_timeout': 2, 'check_interval': 1, 'rest_of_line': 'enforcing'}
                selinux_plugin_test.dotest               -    DEBUG:  SELinux_remote - setup() returned:  0
                     selinux_plugin.eval_status          -    DEBUG:  SELinux_remote - lanmonitor.selinux_plugin.eval_status() called
                        lanmonfuncs.cmd_check            -    DEBUG:  cmd try 1 <['ssh', 'me@testhost', '-p22', '-T', 'sestatus']>
                        lanmonfuncs.cmd_check            -    DEBUG:  cmd try 1 failed (returncode=127) <['ssh', 'me@testhost', '-p22', '-T', 'sestatus']>:  bash: line 1: sestatus: command not found
                        lanmonfuncs.cmd_check            -    DEBUG:  cmd failed on remote system with <check_string mode mismatch> - attempting simplessh connection to <me@testhost>
                        lanmonfuncs.cmd_check            -    DEBUG:  simplessh try 1 <['ssh', 'me@testhost', '-p22', '-T', 'echo', 'hello']>
                        lanmonfuncs.cmd_check            -    DEBUG:  simplessh connection passes.  Return original cmd failure record.
                selinux_plugin_test.dotest               -    DEBUG:  SELinux_remote - eval_status() returned:  {'rslt': 2, 'notif_key': 'SELinux_remote', 'message': '  FAIL: SELinux_remote - testhost - NOT IN EXPECTED STATE (expecting <enforcing>)'}

Test 3 - SELinux remote not running - CRITICAL --------------------------------------------------
                     selinux_plugin.setup                -    DEBUG:  SELinux_remote_CRIT - lanmonitor.selinux_plugin.setup() called:
  {'key': 'SELinux_remote_CRIT', 'tag': 'remote_CRIT', 'host': 'testhost', 'user_host_port': 'me@testhost', 'critical': True, 'cmd_timeout': 2, 'check_interval': 1, 'rest_of_line': 'enforcing'}
                selinux_plugin_test.dotest               -    DEBUG:  SELinux_remote_CRIT - setup() returned:  0
                     selinux_plugin.eval_status          -    DEBUG:  SELinux_remote_CRIT - lanmonitor.selinux_plugin.eval_status() called
                        lanmonfuncs.cmd_check            -    DEBUG:  cmd try 1 <['ssh', 'me@testhost', '-p22', '-T', 'sestatus']>
                        lanmonfuncs.cmd_check            -    DEBUG:  cmd try 1 failed (returncode=127) <['ssh', 'me@testhost', '-p22', '-T', 'sestatus']>:  bash: line 1: sestatus: command not found
                        lanmonfuncs.cmd_check            -    DEBUG:  cmd failed on remote system with <check_string mode mismatch> - attempting simplessh connection to <me@testhost>
                        lanmonfuncs.cmd_check            -    DEBUG:  simplessh try 1 <['ssh', 'me@testhost', '-p22', '-T', 'echo', 'hello']>
                        lanmonfuncs.cmd_check            -    DEBUG:  simplessh connection passes.  Return original cmd failure record.
                selinux_plugin_test.dotest               -    DEBUG:  SELinux_remote_CRIT - eval_status() returned:  {'rslt': 3, 'notif_key': 'SELinux_remote_CRIT', 'message': '  CRITICAL: SELinux_remote_CRIT - testhost - NOT IN EXPECTED STATE (expecting <enforcing>)'}

Test 4 - SELinux expected badmode - setup ERROR --------------------------------------------------
                     selinux_plugin.setup                -    DEBUG:  SELinux_badmode - lanmonitor.selinux_plugin.setup() called:
  {'key': 'SELinux_badmode', 'tag': 'badmode', 'host': 'local', 'user_host_port': 'local', 'critical': True, 'cmd_timeout': 2, 'check_interval': 1, 'rest_of_line': 'enforcingX'}
                     selinux_plugin.setup                -    ERROR:    ERROR:  <SELinux_badmode> INVALID EXPECTED sestatus MODE <enforcingX> PROVIDED - EXPECTING <['enforcing', 'permissive']>
                selinux_plugin_test.dotest               -    DEBUG:  SELinux_badmode - setup() returned:  2

Test 5 - No such host - WARNING --------------------------------------------------
                     selinux_plugin.setup                -    DEBUG:  SELinux_Unknown - lanmonitor.selinux_plugin.setup() called:
  {'key': 'SELinux_Unknown', 'tag': 'Unknown', 'host': 'nosuchhost', 'user_host_port': 'me@nosuchhost', 'critical': True, 'cmd_timeout': 4, 'check_interval': 1, 'rest_of_line': 'enforcing'}
                selinux_plugin_test.dotest               -    DEBUG:  SELinux_Unknown - setup() returned:  0
                     selinux_plugin.eval_status          -    DEBUG:  SELinux_Unknown - lanmonitor.selinux_plugin.eval_status() called
                        lanmonfuncs.cmd_check            -    DEBUG:  cmd try 1 <['ssh', 'me@nosuchhost', '-p22', '-T', 'sestatus']>
                        lanmonfuncs.cmd_check            -    DEBUG:  cmd try 1 failed (returncode=255) <['ssh', 'me@nosuchhost', '-p22', '-T', 'sestatus']>:  ssh: Could not resolve hostname nosuchhost: Name or service not known
                        lanmonfuncs.cmd_check            -    DEBUG:  cmd failed on remote system with <check_string mode mismatch> - attempting simplessh connection to <me@nosuchhost>
                        lanmonfuncs.cmd_check            -    DEBUG:  simplessh try 1 <['ssh', 'me@nosuchhost', '-p22', '-T', 'echo', 'hello']>
                        lanmonfuncs.cmd_check            -    DEBUG:  simplessh try 1 failed (returncode=255) <['ssh', 'me@nosuchhost', '-p22', '-T', 'echo', 'hello']>:  ssh: Could not resolve hostname nosuchhost: Name or service not known
                        lanmonfuncs.cmd_check            -    DEBUG:  simplessh failed with <ssh: Could not resolve hostname nosuchhost: Name or service not known>
                selinux_plugin_test.dotest               -    DEBUG:  SELinux_Unknown - eval_status() returned:  {'rslt': 1, 'notif_key': 'SELinux_Unknown', 'message': '  WARNING: SELinux_Unknown - nosuchhost - ssh: Could not resolve hostname nosuchhost: Name or service not known'}

Test 6 - Known host, unavailable - WARNING --------------------------------------------------
                     selinux_plugin.setup                -    DEBUG:  SELinux_Unavailable - lanmonitor.selinux_plugin.setup() called:
  {'key': 'SELinux_Unavailable', 'tag': 'Unavailable', 'host': 'testhostX', 'user_host_port': 'me@testhostX', 'critical': True, 'cmd_timeout': 4, 'check_interval': 1, 'rest_of_line': 'enforcing'}
                selinux_plugin_test.dotest               -    DEBUG:  SELinux_Unavailable - setup() returned:  0
                     selinux_plugin.eval_status          -    DEBUG:  SELinux_Unavailable - lanmonitor.selinux_plugin.eval_status() called
                        lanmonfuncs.cmd_check            -    DEBUG:  cmd try 1 <['ssh', 'me@testhostX', '-p22', '-T', 'sestatus']>
                        lanmonfuncs.cmd_check            -    DEBUG:  cmd try 1 timeout:  Command '['ssh', 'me@testhostX', '-p22', '-T', 'sestatus']' timed out after 4 seconds
                        lanmonfuncs.cmd_check            -    DEBUG:  cmd failed on remote system with <Command '['ssh', 'me@testhostX', '-p22', '-T', 'sestatus']' timed out after 4 seconds> - attempting simplessh connection to <me@testhostX>
                        lanmonfuncs.cmd_check            -    DEBUG:  simplessh try 1 <['ssh', 'me@testhostX', '-p22', '-T', 'echo', 'hello']>
                        lanmonfuncs.cmd_check            -    DEBUG:  simplessh try 1 timeout:  Command '['ssh', 'me@testhostX', '-p22', '-T', 'echo', 'hello']' timed out after 4.0 seconds
                        lanmonfuncs.cmd_check            -    DEBUG:  simplessh failed with <Command '['ssh', 'me@testhostX', '-p22', '-T', 'echo', 'hello']' timed out after 4.0 seconds>
                selinux_plugin_test.dotest               -    DEBUG:  SELinux_Unavailable - eval_status() returned:  {'rslt': 1, 'notif_key': 'SELinux_Unavailable', 'message': "  WARNING: SELinux_Unavailable - testhostX - cmd_check simplessh timeout:  Command '['ssh', 'me@testhostX', '-p22', '-T', 'echo', 'hello']' timed out after 4.0 seconds"}
